### PR TITLE
feat: Make reports collapsible

### PR DESCRIPTION
**Pull request by c2karansingh**
I think this is necessary because of the overwhelming number of test cases most projects have, which makes looking at a PR cumbersome. For example: At our organization we use this reporter and due to a large number of tests, I end up having to scroll a lot.

I have added a quick fix for now, please suggest if there is a better way to do it.

### CODE REVIEW

**Comment by c2karansingh** [comment]
@scriptnull Please have a look at my changes

**Comment by scriptnull** [comment]
Sure, thanks for the pull request :+1: :heart:

**Review by scriptnull — APPROVED** [review]
:+1:

**Comment by scriptnull** [comment]
Published a new version of the package which you could upgrade to get these changes in your org. `mocha-github-reporter@1.1.0`

**Comment by c2karansingh** [comment]
@scriptnull Tested it, seems to work! Thanks!

**Pull request merged**
